services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: main_database
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: password_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    container_name: adonis_app
    build:
      context: .
    ports:
      - 3333:3333
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  postgres_data: